server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Desafio ACME Let's Encrypt (HTTP-01)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Resposta padrao / Health check
    location / {
        return 200 "Nginx Base Infrastructure is running.\n";
        add_header Content-Type text/plain;
    }
}
